/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/rat/db/set DETECTOR experiment "Watchman_rightcylinder_16m_16m_10pct_5700mm"
/rat/db/set DETECTOR geo_file "Watchman_rightcylinder_16m_16m_10pct_5700mm/Watchman_rightcylinder_16m_16m_10pct_5700mm.geo"
#/rat/db/set DETECTOR detector_factory "Watchman"

#/rat/db/set DETECTOR experiment "Watchman_rightcylinder_16m_16m_20pct_6700mm"
#/rat/db/set DETECTOR geo_file "Watchman_rightcylinder_16m_16m_20pct_6700mm/Watchman_rightcylinder_16m_16m_20pct_6700mm.geo"

/rat/db/set GEO[detector_target_fv] material "wbls_gd_01pct_ly100_WM_0121"
/rat/db/set GEO[detector_target_gb] material "wbls_gd_01pct_ly100_WM_0121"
/rat/db/set GEO[detector_veto1] material "wbls_gd_01pct_ly100_WM_0121"
/rat/db/set GEO[detector_veto2] material "wbls_gd_01pct_ly100_WM_0121"

/run/initialize

/vis/open OGLSQt
/vis/scene/create
/vis/scene/add/trajectories rich smooth
/tracking/storeTrajectory 1
/tracking/FillPointCont 1
/vis/scene/add/volume
/vis/scene/add/hits
/vis/sceneHandler/attach

/vis/viewer/set/upVector 0.0 0.0 1.0
/vis/viewer/set/viewpointThetaPhi 90 180 
/vis/viewer/zoomTo 20
/vis/viewer/set/style s

## Cut a plane through the detector
/vis/viewer/addCutawayPlane -100 0 0 cm 1 0 0

/rat/proc lesssimpledaq
/rat/proc count
/rat/procset update 100
/rat/proclast outroot
/tracking/storeTrajectory 1

#5 MeV electrons at centre of the tank travelling in any direction
/generator/add combo spectrum:point:poisson
/generator/vtx/set e- flat
/generator/pos/set 0 0 0
/generator/rate/set 1.000000
/run/beamOn 100

#/run/beamOn 1
