# Watchman example macro
/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/rat/db/set DETECTOR experiment "Watchman"
/rat/db/set DETECTOR detector_factory "Watchman"
/rat/db/set WATCHMAN_PARAMS photocathode_coverage 0.25

# To activate WBLS
#/rat/db/set GEO[detector] material "Gd_wbls_10pct"
#/rat/db/set GEO[fiducial] material "Gd_wbls_10pct"

/run/initialize

# BEGIN EVENT LOOP
/rat/proc lesssimpledaq
/rat/proc count
/rat/procset update 10

# Use IO.default_output_filename
/rat/proclast outroot
#END EVENT LOOP

/generator/add external external:poisson

/run/beamOn 10000000
