#!/bin/sh
##echo "$1 $2 $3"
case "$(uname -s)" in
    Darwin)
     echo "Mac OS X"
     if test "$1" == "tag"; then
	 docker run --rm -w=/container -v $PWD:/container/ --env RATROOT:/src/rat-pac -it aitwatchman/simulation:$2 /src/rat-pac/tools/bonsai/bonsai /container/$3 /container/$4 $5 $6 $7 $8 
     else
	 docker run --rm -w=/container -v $PWD:/container/ --env RATROOT:/src/rat-pac -it aitwatchman/simulation:latest /src/rat-pac/tools/bonsai/bonsai /container/$1 /container/$2 $3 $4 $5 $6  
     fi
     ;;
    
    Linux)
     echo "Linux Enviorment"
     if test "$1" == "tag"; then
         docker run -u `id -u $USER` --rm -w=/container -v $PWD:/container/ --env RATROOT:/src/rat-pac -it aitwatchman/simulation:$2 /src/rat-pac/tools/bonsai/bonsai /container/$3 /container/$4 $5 $6 $7 $8
     else
         docker run -u `id -u $USER` --rm -w=/container -v $PWD:/container/ --env RATROOT:/src/rat-pac -it aitwatchman/simulation:latest /src/rat-pac/tools/bonsai/bonsai /container/$1 /container/$2 $3 $4 $5 $6
     fi
     ;;
esac
