#!/bin/sh
##echo "$1 $2 $3"

if test "$1" == "tag"; then
  docker run -w=/container -v $PWD:/container/ --env RATROOT:/src/rat-pac -it aitwatchman/simulation:$2 /src/rat-pac/tools/bonsai/bonsai /container/$3 /container/$4 $@
else
  docker run -w=/container -v $PWD:/container/ --env RATROOT:/src/rat-pac -it aitwatchman/simulation:latest /src/rat-pac/tools/bonsai/bonsai /container/$1 /container/$2 $@  
fi
