#!/bin/sh
##echo "$1 $2 $3"


if test "$1" == "tag"; then
  docker run -w=/container -v $PWD:/container/ -it aitwatchman/simulation:$2
else
  docker run -w=/container -v $PWD:/container/ -it aitwatchman/simulation:latest
fi
