#!/bin/sh
##echo "$1 $2 $3"


if  test "$#" -eq 0; then
  echo "docker run -v $PWD:/container/ -it aitwatchman/simulation:latest  /src/rat-pac/bin/root"
  docker run -v $PWD:/container/ -it aitwatchman/simulation:latest  /src/rat-pac/bin/root
elif  test "$1" == "tag"; then
  echo "docker run -v $PWD:/container/ -it aitwatchman/simulation:$2  /src/rat-pac/bin/root ${@:3:$(($#-2))} /container/${!#}"
  docker run -v $PWD:/container/ -it aitwatchman/simulation:$2  /src/rat-pac/bin/root ${@:3:$(($#-2))} /container/${!#}
else
  echo "docker run -v $PWD:/container/ -it aitwatchman/simulation:latest  /src/rat-pac/bin/root ${@:1:$(($#-1))} /container/${!#}"
  docker run -v $PWD:/container/ -it aitwatchman/simulation:latest  /src/rat-pac/bin/root ${@:1:$(($#-1))} /container/${!#}
fi


#
# if  test "$#" -eq 0; then
#   echo "docker run -v $PWD:/container/ -it aitwatchman/simulation:latest  /src/rat-pac/bin/root"
# elif  test "$1" == "tag"; then
#   if test "$#" -eq 2; then
#    echo "A! docker run -v $PWD:/container/ -it aitwatchman/simulation:$2  /src/rat-pac/bin/root "
#   else
#     docker run -v $PWD:/container/ -it aitwatchman/simulation:$2  /src/rat-pac/bin/root ${@:2:$(($#-2))} /container/${!#}"
#   fi
# fi
